### ISSUE TITLE
--include-relations of db savedata command documented but not implemented

### ISSUE THREAD

**Issue by g-tom** [ringo-framework/ringo#86]
There is some documentation around regarding --include-relations (docs/source/start.rst in "Export data" section, as "relations parameter" in the docstring of ringo.lib.imexport.Exporter) and then there is a comment in that class, telling essentially it's not implemented (which can be easily verified):

`#  FIXME: Read support for deprecated "relations" argument?`
`#  Is missing here. (ti) <2017-05-23 14:02>`

Anybody out there who needs this feature? If not, what about removing its documentation and remains of implementation, too?

**Comment by g-tom** [comment]
More remains of --include-relations can be found in  ringo/ringo/scripts/fixture.py.

However, as it says `"Ups... Trying again without relations included"` this doesn't look like something which must be kept neither.

**Comment by toirl** [comment]
After clarification with @g-tom we agreed on removing this option. 

This feature is actually not used anywhere. The initial intenation was to make CSV exports more readable an include string representations of the relations instead of integer values. This seems to be usefull in evaluations based on CSV.

In the meanwhile we have built the https://github.com/ringo-framework/ringo_evaluation extension and a recursive export. Both options are better suited for including relations for evaluations.

**Comment by g-tom** [comment]
> After clarification with @g-tom we agreed on removing this option.

I assume the `fields` attribute of the `Exporter` class can be removed, too. Just saw that it's as well only documented but not implemented. And this one, in contrast to `relations`, is not used anywhere.

**Comment by g-tom** [comment]
> This feature is actually not used anywhere. The initial intenation was to make CSV exports more
> readable

Another purpose might have been to export lists of foreign keys that relate to a n:m-table as indicates this part of the docstring (which has been removed in PR #87):

https://github.com/ringo-framework/ringo/blob/be09dfb376e5779b8744ce631c0074b9ba90bcd2/ringo/lib/imexport.py#L178-L179

That seems useful to create fixtures by export from a database. And this could hardly be superseded by nested JSON (n:m relations would at least imply having the same object multiple times in the file).

**Comment by toirl** [comment]
Your're right. I missed that one. :/
Actually the current fixtures are using the "relations". Take a look in the demo fixtures of ringo or any other application.E.g.in the users.json there are relations mentioned e.g. roles or groups. So at least the importing code can handle that. The "include-relations" flag was AFAIR used to generate those fixtures.

**Comment by toirl** [comment]
On the other hand I do not remeber the last time I used this flag...

**Comment by toirl** [comment]
> That seems useful to create fixtures by export from a database. And this could hardly be superseded by nested JSON (n:m relations would at least imply having the same object multiple times in the file).

Example for users (untestet):

["*", {"groups": ["id"]}, {"roles": ["id"]}]

This should do the trick.

**Comment by g-tom** [comment]
@gsiv,

as a presumably affected person, might you have a look at this issue respectively PR #87? It's all about the CHANGES mentioned in 698122b. Do you eventually need the mentioned export options?

**Comment by gsiv** [comment]
> Do you eventually need the mentioned export options?

I have used `--include-relations` before and I'm pretty sure that it served a purpose then.

But even though the above alternative looks pretty complicated I don't use the option nearly often enough to hold anything back at this point.
